title: Typblography
description: A website with a blog
header_text: Typblography
footer_text: Copyright 2020 Rebecca Fish
header_feature_image: ../uploads/green-nature-science-google-classroom-header-3.png
bannerheight: 20vmax
logo: ../uploads/blog.jpg
favicon: ../uploads/android-chrome-192x192.png
gridlayout: true
fixednavbar: true
upzoom: true
